apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce   # ✅ FIXED
data:
  JWT_SECRET: "secret"
  MONGO_USER_URL: "mongodb://mongo-user:27017/users"
  MONGO_PRODUCT_URL: "mongodb://mongo-product:27017/products"
  MONGO_ORDER_URL: "mongodb://mongo-order:27017/orders"