apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce   # ✅ fixed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: kiran1975/order-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_ORDER_URL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce   # ✅ fixed
spec:
  selector:
    app: order-service
  ports:
    - port: 80
      targetPort: 3003
  type: LoadBalancer   # ✅ for browser access