apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-green
  namespace: ecommerce   # ✅ FIXED
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
      version: green
  template:
    metadata:
      labels:
        app: user-service
        version: green
    spec:
      containers:
        - name: user-service
          image: kiran1975/project4:user-service-v2   # ✅ your image
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"