apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-blue
  namespace: ecommerce   # ✅ fixed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
      version: blue
  template:
    metadata:
      labels:
        app: user-service
        version: blue
    spec:
      containers:
        - name: user-service
          image: kiran1975/project4:user-service-v1   # ✅ your docker image
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
